// Package handler contains HTTP handler functions, one per route.
//
// Each handler receives a DB queries interface (generated by sqlc) and
// returns an http.HandlerFunc. See docs/prd.md REQ-003, REQ-004.
package handler

// ListTeams handles GET /api/v1/teams.
// Returns all 30 NBA teams.
func ListTeams() {
	// TODO: query all teams, encode JSON response
}

// GetTeam handles GET /api/v1/teams/{teamID}.
// Returns team detail with jersey editions.
func GetTeam() {
	// TODO: query team by ID, include jersey editions
}

// GetTeamJerseyStats handles GET /api/v1/teams/{teamID}/jersey-stats.
// Returns team stats aggregated by jersey edition (GP, W, L, Win%, PPG, etc.).
func GetTeamJerseyStats() {
	// TODO: join games + game_jersey_assignments + stats, group by edition
}

// GetPlayerJerseyStats handles GET /api/v1/players/{playerID}/jersey-stats.
// Returns player stats aggregated by jersey edition.
func GetPlayerJerseyStats() {
	// TODO: join player_game_logs + game_jersey_assignments, group by edition
}

// SearchPlayers handles GET /api/v1/players/search?q=.
// Returns matching players by name prefix.
func SearchPlayers() {
	// TODO: ILIKE query on player name
}
