-- Seed all 30 NBA teams for the 2025-26 season.
-- Team IDs match standard NBA abbreviations used in the CSV data.

INSERT INTO teams (id, name, city) VALUES
  ('ATL', 'Atlanta Hawks', 'Atlanta'),
  ('BOS', 'Boston Celtics', 'Boston'),
  ('BKN', 'Brooklyn Nets', 'Brooklyn'),
  ('CHA', 'Charlotte Hornets', 'Charlotte'),
  ('CHI', 'Chicago Bulls', 'Chicago'),
  ('CLE', 'Cleveland Cavaliers', 'Cleveland'),
  ('DAL', 'Dallas Mavericks', 'Dallas'),
  ('DEN', 'Denver Nuggets', 'Denver'),
  ('DET', 'Detroit Pistons', 'Detroit'),
  ('GSW', 'Golden State Warriors', 'Golden State'),
  ('HOU', 'Houston Rockets', 'Houston'),
  ('IND', 'Indiana Pacers', 'Indiana'),
  ('LAC', 'LA Clippers', 'Los Angeles'),
  ('LAL', 'Los Angeles Lakers', 'Los Angeles'),
  ('MEM', 'Memphis Grizzlies', 'Memphis'),
  ('MIA', 'Miami Heat', 'Miami'),
  ('MIL', 'Milwaukee Bucks', 'Milwaukee'),
  ('MIN', 'Minnesota Timberwolves', 'Minnesota'),
  ('NOP', 'New Orleans Pelicans', 'New Orleans'),
  ('NYK', 'New York Knicks', 'New York'),
  ('OKC', 'Oklahoma City Thunder', 'Oklahoma City'),
  ('ORL', 'Orlando Magic', 'Orlando'),
  ('PHI', 'Philadelphia 76ers', 'Philadelphia'),
  ('PHX', 'Phoenix Suns', 'Phoenix'),
  ('POR', 'Portland Trail Blazers', 'Portland'),
  ('SAC', 'Sacramento Kings', 'Sacramento'),
  ('SAS', 'San Antonio Spurs', 'San Antonio'),
  ('TOR', 'Toronto Raptors', 'Toronto'),
  ('UTA', 'Utah Jazz', 'Utah'),
  ('WAS', 'Washington Wizards', 'Washington')
ON CONFLICT (id) DO NOTHING;
